### ISSUE TITLE
Traces shorting 3a and 7a/DNUOS

### ISSUE THREAD

**Issue by nwhelan** [GroooveBob/DASBOB#1]
Thanks for sharing your design! Looking forward to using it. Let me preface this by saying that this is the first time I've had open-source PCBs made, so I'm _certainly_ not ruling out error on my part.

I had these made by JLCPCB and, for whatever reason, I'm having issues with certain pins across all 5 PCBs. Given the consistency of the issue, I'm wondering if two or more traces are too close together. Specifically, I'm having issues with traces 3a and 7a/DNUOS (I'm using a nice!nano v2). Using an ohmmeter, I can bridge the two corresponding pins.

I may try digging out the traces and hand wiring since it only seems to be the two switches which are impacted.

**Comment by GroooveBob** [comment]
hello, im not sure wich version of the pcb you are using im still working and updating that thing because im not fully satisfied ... do you maybe still have the geber file so i can check that out?

**Comment by nwhelan** [comment]
[gerber.zip](https://github.com/GroooveBob/DASBOB/files/9993639/gerber.zip)
Hey there - thanks for the quick reply. Sorry for the delay. Here are the gerber files I used. Pulled as of 11/2 (US). Thanks again for sharing this! In the meantime, I'm just nipping the problematic traces and wiring those switches directly.

**Comment by GroooveBob** [comment]
thanks ... did you used the solder jumper under the mcu?

**Comment by nwhelan** [comment]
Yes, connected BLUETOOTH jumper to connect traces 7/SOUND and 7a/DNUOS.

Do both sides of the board need to have the jumper soldered? I connected that jumper on both sides. From the kicad it seemed like there was no harm in soldering both.

**Comment by GroooveBob** [comment]
i found the issue on the gerber ... i did not update the groundfill :(

**Comment by nwhelan** [comment]
Ah! I was actually able to isolate the impacted traces still and wire those switches directly without too much fuss. All's well that ends well. I'm up and running with it on ZMK.
