### ISSUE TITLE
Are the labels for the buzzer on the PCB backward? 

### ISSUE THREAD

**Issue by twalker** [GroooveBob/DASBOB#6]
Thank you for this creating and releasing this PCB. The thumb clusters located excellently for my hands. I could not help but add a piezo buzzer for the fun of it and oriented the "+" label of the buzzer with the "+" labeled on the PCB--the right pad. The buzzers made no sound until I reversed the orientation. Is the PCB mislabeled?  

Also, the right side does not work with audio enabled and both halves are connected. Does a `AUDIO_PIN_ALT` need to be defined? Do you think that may be the root cause of my issue?

Thanks again for a great layout and PCB design.

"+" on Buzzer appears to go to the "+" printed on the PCB:
![dasbob-piezo](https://github.com/GroooveBob/DASBOB/assets/101895/a5f3899c-f6a3-4b43-be25-fa3b358d1470)

Built with incorrect orientation of buzzer:
![dasbob-built](https://github.com/GroooveBob/DASBOB/assets/101895/fc7e2771-f302-47f5-baa5-a53773507234)

**Comment by GroooveBob** [comment]
ahhh sorry the + is not a label its the conection to die GND-plane ... the buzzer is only working on one side gmk only supports on side :(

**Comment by twalker** [comment]
I see. Thanks for the explanation.
