### ISSUE TITLE
key rollover

### ISSUE THREAD

**Issue by arialdomartini** [GroooveBob/DASBOB#7]
Hello!
That's not an issue, it's more a request to provide more information about the key rollover.
Being diodeless, I assume DASBOB must have some limitations due to ghosting, but I was not able to find any information about that.
The layout I would like to use has some combinations with 3 keys on one part and 2 on the other one.

Thank you!

**Comment by GroooveBob** [comment]
every key has a own pin i dont think there is any limitation

**Comment by arialdomartini** [comment]
I built a couple of DASBOB and can confirm it has a perfect n-key rollover. AMAZING.
Closing this issue!
